// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7PEjvWLPXMEnlU75HuMqmjMXIBNGtD0Q',
    appId: '1:609433526170:web:67ed9761b5f4992cf4a423',
    messagingSenderId: '609433526170',
    projectId: 'learnfirebase-b85fd',
    authDomain: 'learnfirebase-b85fd.firebaseapp.com',
    storageBucket: 'learnfirebase-b85fd.appspot.com',
    measurementId: 'G-TFGCP20Y7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwqgqnSXcMClK7kArl7RrvPro_KnJW0F0',
    appId: '1:609433526170:android:fa14d310a91a8547f4a423',
    messagingSenderId: '609433526170',
    projectId: 'learnfirebase-b85fd',
    storageBucket: 'learnfirebase-b85fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD227h8I1Ec8eQpkvFhELj5FQ_BPHPguT0',
    appId: '1:609433526170:ios:eccb36845c16bda5f4a423',
    messagingSenderId: '609433526170',
    projectId: 'learnfirebase-b85fd',
    storageBucket: 'learnfirebase-b85fd.appspot.com',
    iosBundleId: 'com.example.notes',
  );
}
